### PR TITLE
Tempest test

### PR DESCRIPTION
**Pull request by bodepd**

### CODE REVIEW

**Comment by bodepd** [comment]
so, I got the automated package build/deploy test code working, and it looks like there is a python library conflict on netifaces between the new changes and jorc. I see the following failure:

````
ubuntu@bootstrap1-testjenkins-puppet-rjil-pkg-test-12:~$ jorc get_failures --hosts
Traceback (most recent call last):
  File "/usr/bin/jorc", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2749, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 446, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 459, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 632, in resolve
    raise VersionConflict(dist,req) # XXX put more info here
pkg_resources.VersionConflict: (netifaces 0.8 (/usr/lib/python2.7/dist-packages), Requirement.parse('netifaces>=0.10.4'))
````

I'll sit down today and see if I can resolve this conflict.

**Comment by sorenh** [comment]
@rickysarraf Can you please review this?

**Comment by rickysarraf** [comment]
Yes. THis looks good. oslo.utils depends on netifaces > 0.10.4.
@bodepd has forked the upstream repo from mercurial to git. So we need to keep track of it.

**Comment by sorenh** [comment]
@bodepd, if I understand the comments on https://github.com/JioCloud/autobuild/pull/15 correctly, this isn't done yet? pytz needs to be added, too?

**Comment by bodepd** [comment]
I'm pretty sure I will find that several packages still have conflicts

**Comment by bodepd** [comment]
@sorenh as an update, I got this worked last week, it successfully installed tempest (tempest pretty much failed to run, but at least it tried)

**Comment by rickysarraf** [comment]
On Tuesday 26 May 2015 11:46 PM, Dan Bode wrote:
> @sorenh <https://github.com/sorenh> as an update, I got this worked
> last week, it successfully installed tempest (tempest pretty much
> failed to run, but at least it tried)

@bodepd

Can you share the tempest error messages ?
I believe it should be similar to what I saw when building the package,
and then running in the QA gate environment.

Turns out testr (temest's test execution tool) is very picky on how it
is invoked.

-- 
Ritesh Raj Sarraf
RESEARCHUT - http://www.researchut.com
"Necessity is the mother of invention."

**Comment by bodepd** [comment]
sure, let me kick off another fresh build and I'll link the output

**Comment by bodepd** [comment]
http://jiocloud.rustedhalo.com:8080/job/puppet_rjil_pkg_test/42/console

**Comment by rickysarraf** [comment]
I had a chat with @pandeyop  (QA Team) and the logs show that many other tempest tests have passed. The failures you are seeing are a known issue with tempest in general. 

It will go away when tempest gets rebased to the latest. Currently we are holding off the rebase because we want the (present) tempest packaging chagnes  (PRs) to be merged first.

https://github.com/JioCloud/autobuild/pull/14
https://github.com/JioCloud/autobuild/pull/12
https://github.com/JioCloud/autobuild/pull/16



@pandeyop  can add in the specifics on the many tempest tests that are passing.

**Comment by pandeyop** [comment]
@bodepd @rickysarraf 
I checked out the build: testjenkins-puppet-rjil-pkg-test-42 and ran the full tempest suite on the gcp node.
628 tests ran successfully and there were 417 failures. More details can be found in the testrepository:
/home/jenkins/tempest/.testrepository/3

**Comment by bodepd** [comment]
@sorenh I'm deferring to you to merge this. It seems like everything is working correctly.

NOTE: this needs to be merged in a multi-step process:

1. merge code into autobuild
2. update this patch to point to master of autobuild
3. merge that patch

I'm not even sure what happens between #1 and #2, ideally, we can merge the autobuild code, then re-run a test to make sure that it works before merging, but I assume that this will cause everything to be in a broken state while we do this. I have a feeling that this just needs to be baby-set while it's merged. And I assume that you are the best person to do it. Let me know when you can do this.

**Pull request closed without merging**
