### PR TITLE
Add new repositories that are pre-reqs for tempest

### PR DESCRIPTION
**Pull request by pandeyop**
Additional repositories required for tempest. We are merging tempest into rjil-cicd package.

There are also other repositories that have been rebased to latest to satisfy tempest's requirements/dependencies.....

### CODE REVIEW

**Comment by pandeyop** [comment]
@sorenh @rickysarraf Please review and merge.

**Comment by bodepd** [comment]
Hi,

I'm building out some test automation that we can use to validate this patch, and my first attempt to build packages failed with the following error:

````
PYTHONPATH=/«PKGBUILDDIR»/testtools python -m testtools.run testtools.tests.test_suite
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/«PKGBUILDDIR»/testtools/testtools/run.py", line 267, in <module>
    main(sys.argv, sys.stdout)
  File "/«PKGBUILDDIR»/testtools/testtools/run.py", line 264, in main
    stdout=stdout)
  File "/«PKGBUILDDIR»/testtools/testtools/run.py", line 171, in __init__
    self.parseArgs(argv)
  File "/usr/lib/python2.7/unittest/main.py", line 149, in parseArgs
    self.createTests()
  File "/usr/lib/python2.7/unittest/main.py", line 158, in createTests
    self.module)
  File "/usr/lib/python2.7/unittest/loader.py", line 130, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python2.7/unittest/loader.py", line 115, in loadTestsFromName
    test = obj()
  File "testtools/tests/__init__.py", line 10, in test_suite
    from testtools.tests import (
  File "testtools/tests/test_compat.py", line 6, in <module>
    import linecache2 as linecache
ImportError: No module named linecache2
make[2]: *** [check] Error 1
make[2]: Leaving directory `/«PKGBUILDDIR»/testtools'
dh_auto_build: make -j1 returned exit code 2
make[1]: *** [build/testtools] Error 2
rm python-glanceclient/debian oslo.messaging/debian python-neutronclient/debian posix_ipc/debian python-keystonemiddleware/debian proliantutils/debian oslo.context/debian python-keystoneclient/debian boto/debian oslo.log/debian oslo.utils/debian python-novaclient/debian tempest/debian testtools/debian python-cinderclient/debian oslo.config/debian python-retrying/debian python-six/debian stevedore/debian oslo.concurrency/debian oslo.serialization/debian python-swiftclient/debian tempest-lib/debian ironic/debian msgpack-python/debian oslo.db/debian paramiko/debian oslo.i18n/debian python-websockify/debian python-ironicclient/debian
make[1]: Leaving directory `/«PKGBUILDDIR»'
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2
````

**Comment by rickysarraf** [comment]
On Tuesday 12 May 2015 03:59 AM, Dan Bode wrote:
> |suites = [self.loadTestsFromName(name, module) for name in names] File
> "/usr/lib/python2.7/unittest/loader.py", line 115, in
> loadTestsFromName test = obj() File "testtools/tests/__init__.py",
> line 10, in test_suite from testtools.tests import ( File
> "testtools/tests/test_compat.py", line 6, in <module> import
> linecache2 as linecache ImportError: No module named linecache2
> make[2]: *** [check] Error 1 make[2]: Leaving directory
> `/«PKGBUILDDIR»/testtools' dh_auto_build: make -j1 returned exit code
> 2 make[1]: *** [build/testtools] Error 2 rm python-glanceclient/debian
> oslo.messaging/debian python-neutronclient/debian posix_ipc/debian
> python-keystonemiddleware/debian proliantutils/debian
> oslo.context/debian python-keystoneclient/debian boto/debian
> oslo.log/debian oslo.utils/debian python-novaclient/debian
> tempest/debian testtools/debian python-cinderclient/debian
> oslo.config/debian python-retrying/debian python-six/debian
> stevedore/debian oslo.concurrency/debian oslo.serialization/debian
> python-swiftclient/debian tempest-lib/debian ironic/debian
> msgpack-python/debian oslo.db/debian paramiko/debian oslo.i18n/debian
> python-websockify/debian python-ironicclient/debian make[1]: Leaving
> directory `/«PKGBUILDDIR»' make: *** [build] Error 2
> dpkg-buildpackage: error: debian/rules build gave error exit status 2|

This was one of the pain points of tracking master.

The current master of testtools is > 1.x, which depends on very bleeding
edge toolchain. Thus you see the above failure.

To workaround it, we made an exception to checkout testtools at release
0.9.39 only. This is part of our notes section in the pull request to
get temptest merged.

So, to get it built, please remove the testtools folder after repo sync,
and manually clone version 0.9.39. Then it'll work.


-- 
Ritesh Raj Sarraf
RESEARCHUT - http://www.researchut.com
"Necessity is the mother of invention."

**Comment by rickysarraf** [comment]
https://github.com/JioCloud/autobuild/pull/12
has the details about what all repositories are tightly dependent for tempest to get built proper.

Especially the 3rd conversation comment from @pandeyop in the pull request.

**Comment by bodepd** [comment]
@rickysarraf I'm a little confused. I was told that this patch is ready to be tested, but it looks like you are saying that there is a required manual step? Is the intention to add that step to sync-repo.sh? Is the intention for package builds to not be automated, but come along with a set of steps to be run manually?

**Comment by bodepd** [comment]
I'm not going to perform any manual steps, I will try to update the autobuild definition to pull in the revision that you specified.

**Comment by rickysarraf** [comment]
On Tuesday 12 May 2015 10:32 PM, Dan Bode wrote:
> @rickysarraf <https://github.com/rickysarraf> I'm a little confused. I
> was told that this patch is ready to be tested, but it looks like you
> are saying that there is a required manual step? Is the intention to
> add that step to sync-repo.sh? Is the intention for package builds to
> not be automated, but come along with a set of steps to be run manually?

The patch is in 2 parts.
One for autobuild and the other for repoconf. repoconf needs to rebase
some of its repositories to non-master branches (like the linecache2
example).

So you can't test it unless you rebase the repositories pointed by
repoconf to the right ones. You can override them manually, like I had
mentioned in on of the other comments, where in you git checkout the
desired revision manually.

Once the right repositories are checkout, the entire build is automatic.

-- 
Ritesh Raj Sarraf
RESEARCHUT - http://www.researchut.com
"Necessity is the mother of invention."

**Comment by rickysarraf** [comment]
On Tuesday 12 May 2015 10:33 PM, Dan Bode wrote:
>
> I'm not going to perform any manual steps, I will try to update the
> autobuild definition to pull in the revision that you specified.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JioCloud/repoconf/pull/3#issuecomment-101349616>.
>

Yes. Please. Below are the specific details on the revisions you should
pull.

These are new/revised repositories for the github.com/jiocloud/ forked
repos.

oslo.config
oslo.utils
oslo.i18n
oslo.serializtion
msgpack-python

oslo.concurrency: This one is intact. I have rebased Soren's change on
top of this repo. So this one will just work.

tempest-lib: This was rebased to openstack/master because our forked
repo had diverged from upstream, losing many changes. Hence, I rebased
it to openstack/master.

temptest: Same goes for this repo. It was diverged from upstream. I
rebased it to openstack/master

testtools: This was the tricky one. I haven't rebased it, because I
would like it to be rebased to version 0.9.39, until the upstream
changes (linecache2, traceback2 etc) get stabilized. So when you check
out the repositories, please manually check out version 0.9.39 for
testtools.

-- 
Ritesh Raj Sarraf
RESEARCHUT - http://www.researchut.com
"Necessity is the mother of invention."

**Comment by bodepd** [comment]
superseded by #10

**Pull request closed without merging**
